# Generated by Django 5.2.5 on 2025-08-19 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='emp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('salary', models.IntegerField()),
                ('designation', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=50)),
                ('qualification', models.CharField(max_length=50)),
            ],
        ),
    ]
